server {
    listen 80;
    server_name _;
    index index.php;
    
    root /var/www/public;

    # 隱藏 Nginx 版本資訊 (增加掃描難度)
    server_tokens off;

    # 存取與錯誤日誌設定
    error_log  /var/log/nginx/error.log warn;
    access_log /var/log/nginx/access.log combined;

    # 限制 Request Body 大小 (防止惡意傳大型檔案)
    client_max_body_size 10M;

    # 調整逾時機制
    keepalive_timeout 65;
    client_header_timeout 60;
    client_body_timeout 60;
    send_timeout 60;

    # 開啟優路 Gzip 壓縮
    gzip on;
    gzip_types text/plain text/css application/json application/javascript text/xml application/xml application/xml+rss text/javascript;
    gzip_comp_level 6;

    location / {
        try_files $uri $uri/ /index.php?$query_string;
    }

    # PHP-FPM 連線設定
    location ~ \.php$ {
        try_files $uri =404;
        fastcgi_split_path_info ^(.+\.php)(/.+)$;
        fastcgi_pass app:9000;
        fastcgi_index index.php;
        include fastcgi_params;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        fastcgi_param PATH_INFO $fastcgi_path_info;
        
        # 加固 Buffer
        fastcgi_buffers 16 16k;
        fastcgi_buffer_size 32k;
        
        # 快取 FastCGI 回應 (非強制作為示範)
        fastcgi_read_timeout 60;
    }

    # 限定 .env 或 .git 禁止存取
    location ~ /\.(?!well-known).* {
        deny all;
    }

    # 安全標頭設定 (Security Headers)
    add_header X-Frame-Options "SAMEORIGIN";
    add_header X-Content-Type-Options "nosniff";
    add_header X-XSS-Protection "1; mode=block";
}
