CREATE DATABASE IF NOT EXISTS `edm_db`;

CREATE USER IF NOT EXISTS 'henry_chen'@'%' IDENTIFIED BY 'g@3MC-Kw''EIx$exm+PtX';
GRANT ALL PRIVILEGES ON *.* TO 'henry_chen'@'%' WITH GRANT OPTION;

CREATE USER IF NOT EXISTS 'developer'@'%' IDENTIFIED BY 'wiN]d^yGwwZ$I_&N!Q0n';
GRANT ALL PRIVILEGES ON *.* TO 'developer'@'%' WITH GRANT OPTION;

FLUSH PRIVILEGES;
