CREATE DATABASE IF NOT EXISTS `edm_db`;

CREATE USER IF NOT EXISTS 'developer'@'%' IDENTIFIED BY 'wiN]d^yGwwZ$I_&N!Q0n';
GRANT ALL PRIVILEGES ON *.* TO 'developer'@'%' WITH GRANT OPTION;

FLUSH PRIVILEGES;
